- name: Backend Setup
  hosts: all
  become: true
  tasks:

    - name: Disable current nodejs
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Disable current nodejs
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: latest

    - name: Add application User
      ansible.builtin.user:
        name: expense

    - name: Recursively remove directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create a directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and exttract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes

    - name: Download Node JS
      community.general.npm:
        path: /app
        state: latest

    - name: Copy backend service configuration
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Install Python Mysql
      ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography
        executable: pip3.9

    - name: Load Schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql.dev.makemyhomesmart.co.uk

    - name: Just force systemd to reload system daemon
      ansible.builtin.systemd_service:
        name: backend
        state: restarted
        enabled: yes
        daemon_reload: true
