- name: Install MySQL Server 8.0.x
  hosts: all
  become: true
  tasks:
    - name: Install MySQL Server 8.0.x
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Systemd Restart
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes

    - name: Setup MySql Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

#    - name: Ensure no user named 'sally'@'localhost' exists, also passing in the auth credentials
#      community.mysql.mysql_user:
#        name: root
#        password: ExpenseApp@1

