- name: Install MySQL Server 8.0.x
  hosts: all
  become: true
  tasks:
    - name: Install MySQL Server 8.0.x
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Just force systemd to reload system daemon
      ansible.builtin.systemd_service:
        name: mysqld
        state: start
        enabled: yes

    - name: Ensure no user named 'sally'@'localhost' exists, also passing in the auth credentials
      community.mysql.mysql_user:
        login_user: root
        login_password: ExpenseApp@1

