- name: Install MySQL Server 8.0.x
  hosts: all
  become: true
  tasks:
    - name: Install MySQL Server 8.0.x
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Systemd Restart
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes

    - name: Setup MySql Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

#    - name: Ensure no user named 'sally'@'localhost' exists, also passing in the auth credentials
#      community.mysql.mysql_user:
#        name: root
#        password: ExpenseApp@1

#The above gave me below error:
#  TASK [Ensure no user named 'sally'@'localhost' exists, also passing in the auth credentials] *******************
#  fatal: [ mysql-dev.makemyhomesmart.co.uk ]:
#           FAILED! => {"changed":
#             false, "msg": "A MySQL module is required: for Python 2.7 either PyMySQL, or MySQL-python, or for Python 3.X mysqlclient or PyMySQL. Consider setting ansible_python_interpreter to use the intended Python version." }